# -*- coding: utf-8 -*-
"""Aula7-Telco-Customer-Churn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bjWnl4he6xFukhCO7qepDs5lecasnJk

# Aula 07: Análise Exploratória para Modelagem    

*   **Professor:** Paulo Rogério Pires Manseira
*   **Alunos:** Maruan Biasi El Achkar e Ricardo Falcão Schilieper
*   **GitHub:** github.com/manseiracredit

---

# Importar Dataset - Telco Customer Churn
**Fonte:** https://www.kaggle.com/datasets/blastchar/telco-customer-churn
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

"""# Criar Dataframe"""

import os
import pandas as pd

path_csv = os.path.join(path, 'WA_Fn-UseC_-Telco-Customer-Churn.csv')

df = pd.read_csv(path_csv)

display(df.head(3))

"""#  Carregamento e Diagnóstico"""

display(df.info())

display(df.describe())

display(df.isnull().sum())

"""# Análise da Variável-Alvo ( Churn )"""

import seaborn as sns

sns.countplot(data=df, x='Churn')

"""### Pergunta para Reflexão:
- As classes estão balanceadas? Se um grupo é muito menor que o outro, que desafios isso pode trazer para o nosso modelo?

**Resp.:** Não estão balanceadas, o gráfico nos indica que a quantidade de negativos na métrica alvo "Churn" é mais que o dobro da quantidade de positivos.
Isso pode desencadear em um algorítimo de predição que é melhor em prever negativos do que positivos, o que também acarreta em uma  quantidade significante de falsos negativos.

---

# Relação entre Variáveis Categóricas e o Churn
"""

sns.countplot(x='Contract', hue='Churn', data=df)

sns.countplot(x='InternetService', hue='Churn', data=df)

sns.countplot(x='Partner', hue='Churn', data=df)

"""### Pergunta para Reflexão
- Em qual categoria de contrato (mensal, um ano, dois anos) a barra de 'Churn: Yes' é proporcionalmente maior? O que isso nos diz sobre o comportamento do cliente?

**Resp.:** Na categoria mensal (Month-to-month). Isso nos diz que, clientes assinantes do plano mensal são mais propícios a cancelarem o plano. Acreditamos que essa estatíscias esteja "invertida", nossa interpretação é que, clientes que pretendem cancelar, optam pelo plano mensal para gastarem o mínimo possível.

---

# Relação entre Variáveis Numéricas e o Churn
"""

sns.boxplot(x='Churn', y='tenure', data=df)

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)

"""### Pergunta para Reflexão

- Clientes que cancelam ( Churn: Yes ) tendem a ter um tempo de contrato ( tenure ) maior ou menor? E suas cobranças mensais, são mais altas ou mais baixas? O que as medianas nos boxplots revelam?

**Resp.:** Clientes que cancelam tendem a ter um tempo de contrato menor e também tendem a ter cobranças mensais mais altas. As medianas revelam essas duas tendências mencionadas.
"""