# -*- coding: utf-8 -*-
"""Aula7-Automobile-Data-Set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4IHbLj0xICqdK13CnfB7wcrPHterQVH

# Aula 07: Análise Exploratória para Modelagem    

*   **Professor:** Paulo Rogério Pires Manseira
*   **Alunos:** Maruan Biasi El Achkar e Ricardo Falcão Schilieper
*   **GitHub:** github.com/manseiracredit

---

# Importar Dataset - Automobile Data Set
**Fonte:** https://archive.ics.uci.edu/dataset/10/automobile
"""

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

automobile = fetch_ucirepo(id=10)

"""# Criar Dataframe"""

import pandas as pd

df = automobile.data.features
df['price'] = automobile.data.targets

display(df.head(3))

#  Carregamento e Diagnóstico

display(df.info())

display(df.describe())

display(df.isnull().sum())

# excluir a coluna normalized-losses pois ela tem muitos valores nulos
df = df.drop('normalized-losses', axis=1)
display(df.head())

# excluir as linhas que ainda possuem valores nulos
df = df.dropna()
display(df.head())

# verificar se a limpeza foi realizada cm sucesso
display(df.isnull().sum())

"""# Análise da Variável-Alvo ( price )"""

import seaborn as sns

sns.histplot(df['price'], kde=True)

"""## Interpretação do gráfico acima

O preço médio dos carros é entre 0 e 1. No geral, os preços tendem a ficar ou na média ou acima dela. Sabemos disso pois o gráfico mostra uma assimétria que tende aos valores positivos.

---

### Pergunta para Reflexão:
- A distribuição dos preços é simétrica? Ou é 'puxada' para um dos lados (assimetria)? Isso pode afetar nosso modelo de regressão?

**Resp.:** Não é simétrica. Ela puxa bem mais para o lado positivo (+2 e +3) do que para o lado negativo (-1 e -2). Isso poderia afetar nosso modelo, fazendo com que ele preveja valores mais altos do que o ideal, mas como a assimetria não é gigante, acreditamos que isso não será um problema muito sério nesse caso, mas sim, assimetrias como essa podem acarretar em sérios problemas em modelos de regressão.

---

# Relação entre Variáveis Categóricas e o Preço
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
sns.countplot(x='horsepower', hue='price', data=df, palette=['red', 'orange', 'yellow', 'blue', 'green', 'pink'])
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""## Interpretação do gráfico acima

O gráfico nos mostra que, carros com o preço 3 geralmente tem um motor mais potente, mas no geral, a correlação entre potência e preço não é muito clara. A correlação mais visível nesse gráfico é que nosso dataset possui muito mais carros com poucos cavalos do que com muitos cavalos.

---
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
sns.countplot(x='highway-mpg', hue='price', data=df, palette=['red', 'orange', 'yellow', 'blue', 'green', 'pink'])
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""## Interpretação do gráfico acima

O gráfico nos mostra que, carros com preço 3 tendem a ter consumos piores, isso bate com o gráfico anteior, que mostrava que esses mesmos carros tendem a ter motores mais potentes.

---

### Pergunta para Reflexão
- A relação entre potência e preço parece ser linear? E a relação entre consumo e preço? Qual delas parece ser uma correlação positiva e qual parece ser negativa?

**Resp.:** A relação entre potência e preço não é fortemente linear, mas é possível perceber uma leve tendência à preços mais elevados em carros com mais potência. Já a relação entre consumo e preço é mais clara, mas defitivamente não é linear, o gráfico nos mostra que os carros muito caros tendem a ter consumos piores, já os carros com preços próximos a média de preço tem consumos melhores, enquanto carros abaixo da média tendem a ter consumos um pouco piores.

---

# Relação entre Variáveis Numéricas e o Preço
"""

sns.boxplot(x='price', y='make', data=df)

"""## Interpretação do gráfico acima

O gráfico nos mostra várias coisas interessantes, por exemplo, a montadora toyota tem carros muito baratos e carros muito caros, com várias opções em quase todas as faixas de preço, enquanto por exemplo a Mercedes, costuma fazer carros com preços dentro da média, mas possui modelos (outliers) com valores extremamente elevados.

---
"""

sns.boxplot(x='price', y='body-style', data=df)

"""## Interpretação do gráfico acima

O gráfico acima nos motra que, em média, os carros mais baratos são do tipo "Wagon", mas, se você estiver buscando o carro mais barato de todos, a reposta está no "Sedan", devido aos outliers. O gráfico também mostra que quase todos os conversíveis são extremamente caros.

---

### Pergunta para Reflexão

- Quais fabricantes de carro têm a mediana de preço mais alta? A variabilidade de preços (tamanho da caixa do boxplot) é a mesma para todos os fabricantes?

**Resp.:** As fabricantes "Saab" e "Alfa Romeo" tem as medianas de preços mais altas. Não, a variabilidade não é a mesma para todas, fabricantes como a "Mitsubishi", "Toyota" e "Mercedes Benz" tem variabilidades mais altas, enquanto "Volkswagen" e "BMW" tem variabilidades bem baixas.

---

# Visão Geral com Heatmap
"""

plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

"""## Interpretação do gráfico acima

O gráfico indica várias correlações extremamente interessantes, mas poucas que são relevantes para a nossa métrica alvo. A única variável que tem uma correlação relevante com a métrica alvo preço é o pico máximo de rotações "peak-rpm"

---

# Conclusão

- Com base nesta análise, quais são as 3 a 5 variáveis mais promissoras que você escolheria para treinar um modelo? Justifique sua escolha com base nos gráficos

**Resp.:**
- Fabricante: Pois nos traz informações precisas sobre as faixas de preço dos carros que ela produz.
- Tipo do carro: Pois, parecido com o fabricante, nos traz informações precisas sobre o que esperar do preço de um carro. Por exemplo, conversíveis são sempre caros.
- KM por litro: Baseado no heatmap e countplot, conseguimos ver uma relação que, por mais que fraca, ainda existe e pode nos guiar a melhores resultados.
- Pico de Rotações: O heatmap nos mostra uma clara relação entre peak-rpm e o preço dos carros.
- Horsepower: Parecido com o KM por Litro, a quantidade de cavalos possui uma relação fraca mas existente.
"""